config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'login', to: 'sessions#new'
  post 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get 'password'
    end
  end

  resources :sessions
  resources :customers
  resources :products
  resources :proposals
  resources :suppliers
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string
#  category   :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Customer < ActiveRecord::Base
  belongs_to :user
  has_many :proposals
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :require_user
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = current_user.customers
  end

  def show
  end

  def new
    @customer = current_user.customers.build
  end

  def edit
  end

  def create
    @customer = current_user.customers.build(customer_params)

    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
  def set_customer
    @customer = Customer.where(user_id: current_user).find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :category)
  end
end

app/views/customers/_form.html.slim
.form-group
  = form.label :name, class: 'control-label'
  = form.text_field :name, class: 'form-control'

.form-group
  = form.label :category, class: 'control-label'
  = form.text_field :category, class: 'form-control'

app/views/customers/_index_row_actions.html.slim
.btn-toolbar
  = link_to 'View', customer_path(customer), class: 'btn btn-sm btn-info'
  = link_to 'Edit', edit_customer_path(customer), class: 'btn btn-sm btn-warning'
  = link_to 'Delete', customer_path(customer), method: :delete, confirm: 'Are you sure?', class: 'btn btn-sm btn-danger'

app/views/customers/_index_row_headers.html.slim
th Name
th Category

app/views/customers/_index_rows.html.slim
td= customer.name
td= customer.category

app/views/customers/edit.html.slim
- content_for :page_title, 'Editing Customer'

= form_for @customer do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/customers/index.html.slim
- content_for :page_title, 'All Customers'
.table-responsive
  table.table
    thead
      tr
        = render 'index_row_headers'
        th
    tbody
      - @customers.each do |customer|
        tr
          = render 'index_rows', customer: customer
          td
            .pull-right
              = render 'index_row_actions', customer: customer

br
= link_to 'New Customer', new_customer_path, class: 'btn btn-lg btn-default'

app/views/customers/new.html.slim
- content_for :page_title, 'New Customer'

= form_for @customer do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/customers/show.html.slim
- content_for :page_title, @customer.name

p
  b Category
  =< @customer.category

p: b Proposals
ul
  - @customer.proposals.each do |proposal|
    li= link_to proposal.name, proposal_path(proposal)

.btn-toolbar
  = link_to "Edit #{@customer.name}", edit_customer_path(@customer), class: 'btn btn-lg btn-info'
  = link_to 'View All', customers_path, class: 'btn btn-lg btn-primary'