config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'login', to: 'sessions#new'
  post 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get 'password'
    end
  end

  resources :sessions
  resources :customers
  resources :products
  resources :proposals
  resources :suppliers
end

app/models/proposal.rb
# == Schema Information
#
# Table name: proposals
#
#  id          :integer          not null, primary key
#  name        :string
#  customer_id :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Proposal < ActiveRecord::Base
  belongs_to :customer
  belongs_to :user
  has_many :line_items
  has_many :products, through: :line_items
  accepts_nested_attributes_for :line_items, allow_destroy: true

  delegate :name, to: :customer, prefix: true

end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :require_user
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  def index
    @proposals = current_user.proposals
  end

  def show
  end

  def new
    @proposal = current_user.proposals.build
  end

  def edit
  end

  def create
    @proposal = current_user.proposals.build(proposal_params)
    if @proposal.save
      redirect_to @proposal, notice: 'Proposal was successfully created.'
    else
      render :new
    end
  end

  def update
    if @proposal.update(proposal_params)
      redirect_to @proposal, notice: 'Proposal was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @proposal.destroy
    redirect_to proposals_url, notice: 'Proposal was successfully destroyed.'
  end

  private
  def set_proposal
    @proposal = Proposal.where(user_id: current_user).includes(:line_items).find(params[:id])
  end

  def proposal_params
    params.require(:proposal).permit(:name, :customer_id, :line_items_attributes => [:id, :product_id, :proposal_id, :quantity, :discount, :notes, :_destroy])
  end
end

app/views/proposals/_form.html.slim
.form-group
  = form.label :name, class: 'control-label'
  = form.text_field :name, class: 'form-control'
.form-group
  = form.label :customer_id, 'Customer'
  = form.collection_select :customer_id, current_user.customers, :id, :name, {}, class: 'form-control'

  h2 Items
  = form.fields_for :line_items do |f|
    = render 'line_item_fields', f: f
  = link_to_add_fields 'Add Product', form, :line_items

app/views/proposals/_index_row_actions.html.slim
.btn-toolbar
  = link_to 'View', proposal_path(proposal), class: 'btn btn-sm btn-info'
  = link_to 'Edit', edit_proposal_path(proposal), class: 'btn btn-sm btn-warning'
  = link_to 'Delete', proposal_path(proposal), method: :delete, confirm: 'Are you sure?', class: 'btn btn-sm btn-danger'

app/views/proposals/_index_row_headers.html.slim
th Name
th Customer
th Product SKUs
th Total # of products
th Total cost

app/views/proposals/_index_rows.html.slim
td= proposal.name
td= proposal.customer_name
td= proposal.line_items.count
td= proposal.line_items.map(&:quantity).inject(:+)
td= number_to_currency(proposal.line_items.map(&:line_price).inject(:+), precision: 4)

app/views/proposals/_line_item_fields.html.slim
.row
  .col-sm-3
    .form-group
      = f.label :product_id, 'Product name'
      = f.grouped_collection_select :product_id, Supplier.all, :products, :name, :id, :name, { prompt: 'Select a product:' }, class: 'form-control'
  .col-sm-1
    .form-group
      = f.label :quantity, class: 'control-label'
      = f.number_field :quantity, class: 'form-control'
  .col-sm-1
    .form-group
      = f.label :discount, class: 'control-label'
      = f.number_field :discount, class: 'form-control'
  .col-sm-5
    .form-group
      = f.label :notes, class: 'control-label'
      = f.text_field :notes, class: 'form-control'
  .col-sm-1
    .form-group
      = f.label :price
      p.product-price
  .col-sm-1
    .form-group
      = f.label :_destroy, 'Remove'
      = f.check_box :_destroy

app/views/proposals/edit.html.slim
- content_for :page_title, 'Editing Proposal'

= form_for @proposal do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/proposals/index.html.slim
- content_for :page_title, 'All Proposals'
.table-responsive
  table.table
    thead
      tr
        = render 'index_row_headers'
        th
    tbody
      - @proposals.each do |proposal|
        tr
          = render 'index_rows', proposal: proposal
          td
            .pull-right
              = render 'index_row_actions', proposal: proposal

br
= link_to 'New Proposal', new_proposal_path, class: 'btn btn-lg btn-default'

app/views/proposals/new.html.slim
- content_for :page_title, 'New Proposal'

= form_for @proposal do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/proposals/show.html.slim
- content_for :page_title, @proposal.name

p
  b Customer:
  =< @proposal.customer.name

p: b Products
.table-responsive
  table.table
    thead
      tr
        th Name
        th Quantity
        th Price
        th Discount
        th Line Price
    tbody
      - @proposal.line_items.each do |line_item|
        tr
          td= link_to line_item.product.name, product_path(line_item.product)
          td= line_item.quantity
          td= number_to_currency(line_item.product.price, precision: 4)
          td= line_item.discount
          td= number_to_currency(line_item.line_price, precision: 4)
h2
  | Proposal Total:
  span
    - cost = @proposal.line_items.map { |li| li.product.price * li.quantity }.inject(:+)
    =< number_to_currency(cost, precision: 4)

.btn-toolbar
  = link_to "Edit #{@proposal.name}", edit_proposal_path(@proposal), class: 'btn btn-lg btn-info'
  = link_to 'View All', proposals_path, class: 'btn btn-lg btn-primary'