config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'login', to: 'sessions#new'
  post 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get 'password'
    end
  end

  resources :sessions
  resources :customers
  resources :products
  resources :proposals
  resources :suppliers
end

app/models/supplier.rb
# == Schema Information
#
# Table name: suppliers
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Supplier < ActiveRecord::Base
  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :require_user
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def edit
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to @supplier, notice: 'Supplier was successfully created.'
    else
      render :new
    end
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to @supplier, notice: 'Supplier was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @supplier.destroy
    redirect_to suppliers_url, notice: 'Supplier was successfully destroyed.'
  end

  private
  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:name)
  end
end

app/views/suppliers/_form.html.slim
.form-group
  = form.label :name, class: 'control-label'
  = form.text_field :name, class: 'form-control'

app/views/suppliers/_index_row_actions.html.slim
.btn-toolbar
  = link_to 'View', supplier_path(supplier), class: 'btn btn-sm btn-info'
  = link_to 'Edit', edit_supplier_path(supplier), class: 'btn btn-sm btn-warning'
  = link_to 'Delete', supplier_path(supplier), method: :delete, confirm: 'Are you sure?', class: 'btn btn-sm btn-danger'

app/views/suppliers/_index_row_headers.html.slim
th Name

app/views/suppliers/_index_rows.html.slim
td= supplier.name

app/views/suppliers/edit.html.slim
- content_for :page_title, 'Editing Supplier'

= form_for @supplier do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/suppliers/index.html.slim
- content_for :page_title, 'All Suppliers'
.table-responsive
  table.table
    thead
      tr
        = render 'index_row_headers'
        th
    tbody
      - @suppliers.each do |supplier|
        tr
          = render 'index_rows', supplier: supplier
          td
            .pull-right
              = render 'index_row_actions', supplier: supplier

br
= link_to 'New Supplier', new_supplier_path, class: 'btn btn-lg btn-default'

app/views/suppliers/new.html.slim
- content_for :page_title, 'New Supplier'

= form_for @supplier do |form|
  = render 'form', form: form
  = form.submit 'Submit', class: 'btn btn-lg btn-success'

app/views/suppliers/show.html.slim
- content_for :page_title, @supplier.name


p: b Products
ul
  - @supplier.products.each do |product|
    li= link_to product.name, product_path(product)

.btn-toolbar
  = link_to "Edit #{@supplier.name}", edit_supplier_path(@supplier), class: 'btn btn-lg btn-info'
  = link_to 'View All', suppliers_path, class: 'btn btn-lg btn-primary'