config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get 'login', to: 'sessions#new'
  post 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'

  resources :users do
    member do
      get 'password'
    end
  end

  resources :sessions
  resources :customers
  resources :products
  resources :proposals
  resources :suppliers
end

app/views/layouts/_buttons.html.slim
.btn-toolbar
  = link_to 'Customers', customers_path, class: 'btn btn-default btn-lg'
  = link_to 'Suppliers', suppliers_path, class: 'btn btn-default btn-lg'
  = link_to 'Products', products_path, class: 'btn btn-default btn-lg'
  = link_to 'Proposals', proposals_path, class: 'btn btn-default btn-lg'

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-static-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed type='button' data-toggle='collapse' data-target='#navbar-collapse'
        .sr-only Toggle navigation
        .icon-bar
        .icon-bar
        .icon-bar
      = link_to 'Sales Proposal Maker', '/', class: 'navbar-brand'
    .collapse.navbar-collapse#navbar-collapse
      - if current_user.guest?
        p.navbar-text Welcome #{current_user.name}
      ul.nav.navbar-nav.navbar-right
        - if current_user.guest?
          li= link_to 'Log In', login_path
          li= link_to 'Sign Up', new_user_path
        - else
          li= link_to current_user.name, user_path(current_user)
          li= link_to 'Log Out', logout_path, method: :post
          - nav_links.each do |name, url|
            li= link_to name, url

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width, initial-scale=1'
    title= full_title(yield(:page_title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render 'layouts/navbar'
    .container
      h1 = yield(:page_title)
      = yield